/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import javax.swing.JOptionPane;

/**
 *
 * @version 15 de abril del 2019
 * @author Hernaldo Valerio Pineda
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    Matris_Caballo o_matris_caballo; 
    
    public JFrmPrincipal() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTxTImpresion_Matris = new javax.swing.JTextArea();
        jBttnCambiarTamanno_Matris = new javax.swing.JButton();
        jBttnElegirCoordenadas_Salida = new javax.swing.JButton();
        jBttnCalcularRecorrido = new javax.swing.JButton();
        jBttnMostrarTiempo_Caballo = new javax.swing.JButton();
        jBttnImprimirRecorrido = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTxTImpresion_Matris.setColumns(20);
        jTxTImpresion_Matris.setRows(5);
        jScrollPane1.setViewportView(jTxTImpresion_Matris);

        jBttnCambiarTamanno_Matris.setText("Cambiar");
        jBttnCambiarTamanno_Matris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnCambiarTamanno_MatrisActionPerformed(evt);
            }
        });

        jBttnElegirCoordenadas_Salida.setText("Elegir");
        jBttnElegirCoordenadas_Salida.setToolTipText("");
        jBttnElegirCoordenadas_Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnElegirCoordenadas_SalidaActionPerformed(evt);
            }
        });

        jBttnCalcularRecorrido.setText("Calcular");

        jBttnMostrarTiempo_Caballo.setText("Mostrar");

        jBttnImprimirRecorrido.setText("Imprimir ");

        jLabel1.setText("Modificar el tamaño de la matris");

        jLabel2.setText("Elegir las coordenadas de salida");

        jLabel3.setText("Calcular el recorrido");

        jLabel4.setText("Mostrar tiempo requerido para el calculo");

        jLabel5.setText("Imprimir recorrido");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Matriz del caballo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jBttnImprimirRecorrido)
                    .addComponent(jLabel1)
                    .addComponent(jBttnElegirCoordenadas_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jBttnCalcularRecorrido)
                    .addComponent(jBttnMostrarTiempo_Caballo)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jBttnCambiarTamanno_Matris))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBttnCambiarTamanno_Matris)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBttnElegirCoordenadas_Salida)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBttnCalcularRecorrido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBttnMostrarTiempo_Caballo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBttnImprimirRecorrido)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnCambiarTamanno_MatrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnCambiarTamanno_MatrisActionPerformed
        int v_fila = Integer.parseInt(JOptionPane.showInputDialog("Digite el número de las filas de l,a matris"));
        int v_columna = Integer.parseInt(JOptionPane.showInputDialog("Digite el número de las columnas de la matris"));
        o_matris_caballo = new Matris_Caballo(v_fila, v_columna);
        this.jTxTImpresion_Matris.setText(o_matris_caballo.ImprimirMatris());
    }//GEN-LAST:event_jBttnCambiarTamanno_MatrisActionPerformed

    private void jBttnElegirCoordenadas_SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnElegirCoordenadas_SalidaActionPerformed
        int v_fila = Integer.parseInt(JOptionPane.showInputDialog("Digite el número de la filas en donde desee ubicar el caballo"));
        int v_columna = Integer.parseInt(JOptionPane.showInputDialog("Digite el número de la columna en donde desee ubicar el caballo"));
        o_matris_caballo.PosicionarCaballo(v_fila, v_columna);
        this.jTxTImpresion_Matris.setText(o_matris_caballo.ImprimirMatris());
    }//GEN-LAST:event_jBttnElegirCoordenadas_SalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnCalcularRecorrido;
    private javax.swing.JButton jBttnCambiarTamanno_Matris;
    private javax.swing.JButton jBttnElegirCoordenadas_Salida;
    private javax.swing.JButton jBttnImprimirRecorrido;
    private javax.swing.JButton jBttnMostrarTiempo_Caballo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxTImpresion_Matris;
    // End of variables declaration//GEN-END:variables
}
